# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bcrypt', '~> 3.1', '>= 3.1.16'
gem 'irb', '~> 1.3', '>= 1.3.6', group: :development
gem 'solargraph', group: :development
gem 'yard', '~> 0.9.26', group: :development
